services:

  redis-storage:
    image: redis
    volumes:
      - ./redis:/data

  library:
    build: ./library
    environment:
      - PORT=80
      - COUNTER_URL=http://counter
    ports:
      - 3002:80
    depends_on:
      - counter

  counter:
    build: ./counter
    environment:
      - PORT=80
      - REDIS_URL=redis://redis-storage
    ports:
      - 3003:80
    depends_on:
      - redis-storage

